/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "Game.h"

/* Header for class _Included_com_example_jligameenginetest_Input */

#ifndef _Included_com_example_jligameenginetest_Input
#define _Included_com_example_jligameenginetest_Input
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_example_jligameenginetest_JLIGameEngineTestLib
 * Method:    onTouchDown
 * Signature: (Ljava/util/Vector;)V
 */
JNIEXPORT void JNICALL Java_com_example_jligameenginetest_JLIGameEngineTestLib_onTouchDown
  (JNIEnv *env, jclass cls, jobject obj)
{
	touch_down();
}

/*
 * Class:     com_example_jligameenginetest_JLIGameEngineTestLib
 * Method:    onTouchUp
 * Signature: (Ljava/util/Vector;)V
 */
JNIEXPORT void JNICALL Java_com_example_jligameenginetest_JLIGameEngineTestLib_onTouchUp
  (JNIEnv *env, jclass cls, jobject obj)
{
	touch_up();
}

/*
 * Class:     com_example_jligameenginetest_JLIGameEngineTestLib
 * Method:    onTouchMove
 * Signature: (Ljava/util/Vector;)V
 */
JNIEXPORT void JNICALL Java_com_example_jligameenginetest_JLIGameEngineTestLib_onTouchMove
  (JNIEnv *env, jclass cls, jobject obj)
{
	touch_move();
}

JNIEXPORT void JNICALL Java_com_example_jligameenginetest_JLIGameEngineTestLib_onTouchCancel
(JNIEnv *env, jclass cls, jobject obj)
{
	touch_cancelled();
}

#ifdef __cplusplus
}
#endif
#endif
